version: '3.9'

services:
  neo4j:
    image: neo4j:4.4.7-community
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./db-data:/data
    environment:
      - NEO4J_AUTH=none
