version: '3.9'

services:
  mongo:
    image: mongo:5.0.7
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
